apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: idhpt03ei-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: idhpt03ei-go 
  name: idhpt03ei-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: idhpt03ei-go 
